name: turtlebot-demo
version: 1.0.1
summary: ROS Turtlebot Demo for Ubuntu Core
description: |
  Robot moves in confined area based on detecting perimeter with robots IR sensors as well as using bump sensor
   to stop if it impacts something and button B0 to restart movement and buttons B1 and B2 to stop robot.
   Calibrate command will run rostopic echo /mobile_base/sensors/core to displa realtime sensor data.
   Environment is Kinetic ROS on Ubuntu with additional Turtlebot packages.
   github: https://github.com/mjbenz/Ubuntu-Core-Turtlebot-Demo
confinement: devmode
grade: devel

apps:
  bringup:
    command: bin/bringup
    plugs:
    - network
    - network-bind
    - serial-port

  demo:
    command: bin/demo
    plugs:
    - network
    - network-bind

  teleop:
    command: bin/teleop
    plugs:
    - network
    - network-bind

  calibrate:
    command: bin/calibrate
    plugs:
    - network
    - network-bind

parts:
  ros-project:
    plugin: catkin
    source: .
    catkin-packages:
    - move_confined
    rosdistro: kinetic
    stage-packages:
    - ros-kinetic-ros-base
    - ros-kinetic-turtlebot-bringup
    - ros-kinetic-kobuki-core
    #- gcc
    #- g++
    include-roscore: true

  file-copy:
    plugin: dump
    source: .
    organize:
      setup/bringup: bin/
      setup/demo: bin/
      setup/teleop: bin/
      setup/calibrate: bin/
