#!/bin/sh

#export ROS_MASTER_URI=http://localhost:11311
export ROS_HOSTNAME=localhost
export ROS_IP=localhost
export TURTLEBOT_BASE=kobuki

# This assumes Kobuki will be connected at ttyUSB0, if it is another /dev the next entry needs to be changed.
export TURTLEBOT_SERIAL_PORT=/dev/ttyUSB0

exec roslaunch turtlebot_teleop keyboard_teleop.launch
